name       : perl-text-bibtex
version    : '0.89'
release    : 10
source     :
    - https://cpan.metacpan.org/authors/id/A/AM/AMBS/Text-BibTeX-0.89.tar.gz : 88a78ebf088ec7502f401c5a2b138c862cf5458534b773223bbf3aaf41224196
homepage   : https://metacpan.org/pod/Text::BibTeX
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Text::BibTeX - interface to read and parse BibTeX files
description: |
    The Text::BibTeX module serves mainly as a high-level introduction to the Text::BibTeX library, for both code and documentation purposes. The code loads the two fundamental modules for processing BibTeX files (Text::BibTeX::File and Text::BibTeX::Entry), and this documentation gives a broad overview of the whole library that isn't available in the documentation for the individual modules that comprise it.
builddeps  :
    - perl-config-autoconf
    - perl-extutils-libbuilder
    - perl-module-build
rundeps    :
    - perl-scalar-list-utils
patterns   : /*
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
