name       : perl-text-bibtex
version    : 0.77
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/A/AM/AMBS/Text-BibTeX-0.77.tar.gz : 6459bb9d93ab5520959ce0ebd28cdf34dcf685774e40f377bcc39c3935ea6e4e
license    : Artistic-2.0
component  : programming.perl
summary    : Text::BibTeX - interface to read and parse BibTeX files
description: |
    Text::BibTeX - interface to read and parse BibTeX files
libsplit   : no
builddeps  :
    - perl-config-autoconf
    - perl-extutils-libbuilder
    - perl-module-build
rundeps    :
    - perl-scalar-list-utils
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
